version: "3.7"
services:
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 80:80
    volumes:
      - ./db/:/data/db
  server:
    image: rickypazd/aeronave-java
    build: ./aeronave
    network_mode: "service:database"
  web:
    image: nginx:latest
    network_mode: "service:database"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
